"""Tests for `ClaudeAgentSDKProvider`.

None of these tests require the real `claude-agent-sdk` package or a real
`claude` CLI: the fake `query`/`ClaudeAgentOptions`/`ResultMessage`
objects below are injected via the provider's `_query_fn`/`_options_cls`/
`_result_message_cls` test seams (see `providers/claude_sdk.py`'s class
docstring), so this file exercises the provider's own orchestration logic
-- allow-list composition, prompt assembly, git introspection, self-check
execution, termination mapping -- against a real (but disposable, locally
created) Git repository standing in for an isolated working tree.

One test (`test_constructor_raises_when_sdk_unavailable`) intentionally
exercises the *real*, uninjected import path, to assert this environment's
actual state: `claude-agent-sdk` is not installed here, so the
constructor must fail fast and loud rather than fail later inside
`execute()`. That test is skipped automatically if the package ever does
become available in whatever environment runs this suite.
"""
from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any, List

import pytest

from ai_sdlc.capabilities.coding import (
    CodingRequest,
    MalformedResponseError,
    ProviderError,
    TerminationReason,
)
from ai_sdlc.capabilities.providers import claude_sdk as claude_sdk_module
from ai_sdlc.capabilities.providers.claude_sdk import ClaudeAgentSDKProvider


# -- fakes standing in for the claude-agent-sdk package -----------------------


class _FakeResultMessage:
    def __init__(
        self,
        *,
        is_error: bool = False,
        num_turns: int | None = None,
        session_id: str = "sess-1",
        total_cost_usd: float = 0.02,
        result: str = "Implemented the requested change.",
    ):
        self.is_error = is_error
        self.num_turns = num_turns
        self.session_id = session_id
        self.total_cost_usd = total_cost_usd
        self.result = result


class _FakeAssistantMessage:
    """Stand-in for a non-terminal SDK message the provider must ignore
    when scanning for the terminal `ResultMessage`."""


class _FakeOptions:
    def __init__(self, **kwargs: Any):
        self.kwargs = kwargs


def _make_fake_query(*, on_call=None, messages: List[Any] | None = None):
    messages = messages if messages is not None else [_FakeResultMessage()]

    async def _fake_query(*, prompt: str, options: _FakeOptions):
        if on_call is not None:
            on_call(prompt, options)
        for message in messages:
            yield message

    return _fake_query


def _provider(**messages_kwargs) -> tuple[ClaudeAgentSDKProvider, dict]:
    captured: dict = {}

    def _on_call(prompt: str, options: _FakeOptions) -> None:
        captured["prompt"] = prompt
        captured["options"] = options

    messages = messages_kwargs.pop("messages", None)
    provider = ClaudeAgentSDKProvider(
        _query_fn=_make_fake_query(on_call=_on_call, messages=messages),
        _options_cls=_FakeOptions,
        _result_message_cls=_FakeResultMessage,
        **messages_kwargs,
    )
    return provider, captured


# -- fixtures ------------------------------------------------------------------


@pytest.fixture
def git_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git = lambda *args: subprocess.run(
        ["git", *args], cwd=repo, check=True, capture_output=True, text=True
    )
    _git("init", "-b", "main")
    _git("config", "user.email", "forge@example.com")
    _git("config", "user.name", "Forge Test")
    (repo / "README.md").write_text("hello\n")
    _git("add", ".")
    _git("commit", "-m", "init")
    _git("checkout", "-b", "forge/example-change")
    return repo


def _base_request(working_tree_path: Path, **overrides: Any) -> CodingRequest:
    fields = dict(
        task_title="Add export endpoint",
        task_summary="Add a CSV export endpoint to the order service.",
        components_affected=["OrderService"],
        working_tree_path=str(working_tree_path),
        allowed_tools=["Read", "Write", "Edit", "Bash"],
        allowed_commands=["git", "pytest"],
    )
    fields.update(overrides)
    return CodingRequest(**fields)


def _commit_a_change(repo: Path, filename: str = "src/new_file.py") -> None:
    target = repo / filename
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("# generated by the (fake) coding agent\n")
    subprocess.run(["git", "add", "."], cwd=repo, check=True, capture_output=True)
    subprocess.run(
        ["git", "commit", "-m", "agent change"], cwd=repo, check=True, capture_output=True
    )


# -- constructor ----------------------------------------------------------------


def test_constructor_raises_when_sdk_unavailable():
    if claude_sdk_module.SDK_IMPORT_ERROR is None:
        pytest.skip("claude-agent-sdk is installed in this environment; nothing to assert here")
    with pytest.raises(ProviderError):
        ClaudeAgentSDKProvider()


def test_constructor_succeeds_with_injected_fakes():
    provider, _ = _provider()
    assert isinstance(provider, ClaudeAgentSDKProvider)


# -- happy path -------------------------------------------------------------------


def test_execute_returns_valid_result_and_reads_git_ground_truth(git_repo: Path):
    def _on_call_with_commit(prompt, options):
        _commit_a_change(Path(options.kwargs["cwd"]))

    provider = ClaudeAgentSDKProvider(
        _query_fn=_make_fake_query(on_call=_on_call_with_commit),
        _options_cls=_FakeOptions,
        _result_message_cls=_FakeResultMessage,
    )
    request = _base_request(git_repo)

    result = provider.execute(request)

    assert result.branch_name == "forge/example-change"
    assert result.files_changed == ["src/new_file.py"]
    assert result.provider_name == "claude_agent_sdk"
    assert result.terminated_reason == TerminationReason.COMPLETED
    assert result.summary == "Implemented the requested change."
    assert result.metadata["session_id"] == "sess-1"


def test_execute_prompt_includes_task_fields(git_repo: Path):
    provider, captured = _provider()
    request = _base_request(
        git_repo,
        functional_requirements=["Support CSV export"],
        standards_instructions="Use FastAPI conventions.",
    )

    provider.execute(request)

    prompt = captured["prompt"]
    assert "Add export endpoint" in prompt
    assert "Support CSV export" in prompt
    assert "Use FastAPI conventions." in prompt
    assert request.working_tree_path in prompt


# -- allow-list composition -------------------------------------------------------


def test_bash_is_never_bare_allowed(git_repo: Path):
    provider, captured = _provider()
    request = _base_request(git_repo, allowed_tools=["Read", "Bash"], allowed_commands=["git"])

    provider.execute(request)

    allowed = captured["options"].kwargs["allowed_tools"]
    assert "Bash" not in allowed
    assert "Bash(git *)" in allowed
    assert "Read" in allowed


def test_no_bash_entries_when_allowed_commands_empty(git_repo: Path):
    provider, captured = _provider()
    request = _base_request(git_repo, allowed_tools=["Read", "Bash"], allowed_commands=[])

    provider.execute(request)

    allowed = captured["options"].kwargs["allowed_tools"]
    assert not any(entry.startswith("Bash") for entry in allowed)


def test_git_push_always_disallowed(git_repo: Path):
    provider, captured = _provider()
    request = _base_request(git_repo, allowed_commands=["git", "push"])

    provider.execute(request)

    assert "Bash(git push *)" in captured["options"].kwargs["disallowed_tools"]


def test_permission_mode_is_dont_ask(git_repo: Path):
    provider, captured = _provider()
    provider.execute(_base_request(git_repo))
    assert captured["options"].kwargs["permission_mode"] == "dontAsk"


def test_max_turns_defaults_and_overrides(git_repo: Path):
    provider, captured = _provider()
    provider.execute(_base_request(git_repo))
    assert captured["options"].kwargs["max_turns"] == 40  # DEFAULT_MAX_STEPS

    provider, captured = _provider()
    provider.execute(_base_request(git_repo, max_steps=5))
    assert captured["options"].kwargs["max_turns"] == 5


# -- termination mapping -----------------------------------------------------------


def test_step_budget_exhausted(git_repo: Path):
    provider, _ = _provider(messages=[_FakeResultMessage(num_turns=5)])
    request = _base_request(git_repo, max_steps=5)

    result = provider.execute(request)

    assert result.terminated_reason == TerminationReason.STEP_BUDGET_EXHAUSTED


def test_provider_reported_failure(git_repo: Path):
    provider, _ = _provider(messages=[_FakeResultMessage(is_error=True, num_turns=1)])
    request = _base_request(git_repo, max_steps=40)

    result = provider.execute(request)

    assert result.terminated_reason == TerminationReason.PROVIDER_REPORTED_FAILURE


def test_provider_error_when_no_result_message_ever_arrives(git_repo: Path):
    provider = ClaudeAgentSDKProvider(
        _query_fn=_make_fake_query(messages=[_FakeAssistantMessage()]),
        _options_cls=_FakeOptions,
        _result_message_cls=_FakeResultMessage,
    )
    with pytest.raises(ProviderError):
        provider.execute(_base_request(git_repo))


# -- self-check ---------------------------------------------------------------------


def test_self_check_skipped_when_no_commands_configured(git_repo: Path):
    provider, _ = _provider()
    result = provider.execute(_base_request(git_repo))

    assert result.self_check.build_passed is None
    assert result.self_check.tests_passed is None
    assert result.self_check.skipped_reason is not None


def test_self_check_passes_and_fails_correctly(git_repo: Path):
    provider, _ = _provider()
    request = _base_request(git_repo, build_commands=["true"], test_commands=["false"])

    result = provider.execute(request)

    assert result.self_check.build_passed is True
    assert result.self_check.tests_passed is False
    assert result.self_check.commands_run == ["true", "false"]


# -- working tree validation ---------------------------------------------------------


def test_execute_rejects_nonexistent_working_tree_path(tmp_path: Path):
    provider, _ = _provider()
    request = _base_request(tmp_path / "does-not-exist")

    with pytest.raises(ProviderError):
        provider.execute(request)


def test_execute_rejects_non_git_directory(tmp_path: Path):
    plain_dir = tmp_path / "not-a-repo"
    plain_dir.mkdir()
    provider, _ = _provider()
    request = _base_request(plain_dir)

    with pytest.raises(ProviderError):
        provider.execute(request)


# -- malformed downstream result -------------------------------------------------------


def test_malformed_response_error_when_result_text_and_everything_else_still_valid(
    git_repo: Path,
):
    """Even a pathological empty-string `result` on the fake message must
    still degrade to the task-title-derived summary rather than raising --
    MalformedResponseError is reserved for outcomes that truly can't
    satisfy CodingResult (e.g. a provider-internal bug), not for an absent
    natural-language summary, which this provider treats as optional
    color, not required data."""
    provider, _ = _provider(messages=[_FakeResultMessage(result="")])
    result = provider.execute(_base_request(git_repo))
    assert result.summary == "Applied changes for: Add export endpoint."


def test_execute_is_safe_to_call_from_within_a_running_event_loop(git_repo: Path):
    import asyncio

    provider, _ = _provider()
    request = _base_request(git_repo)

    async def _caller():
        return provider.execute(request)

    result = asyncio.run(_caller())
    assert result.branch_name == "forge/example-change"
